input:
  keyboard:
    mapping:
      cursorUp: ArrowUp
      cursorDown: ArrowDown
      cursorLeft: ArrowLeft
      cursorRight: ArrowRight
      cameraUp: PageUp
      cameraDown: PageDown
  mouse:
  gamepad:


assets:
  scene:
    cache:
      maxSize: 3
  terrain:
    cache:
      maxSize: 3
  texture:
    cache:
      maxSize: 16


logic:
  ai:
  gameplay:
    world:
      defaultScene: test_a
  gui:
    tile:
      inputWidth: 16
      inputHeight: 16
      inGameWidth: 128
      inGameHeight: 128
  online:


output:
  audio:
  graphic:
