export default {
  INITIALIZED: 1,
  CREATING: 2,
  CREATED: 3,
  STARTING: 4,
  STARTED: 5,
  RESUMING: 6,
  RESUMED: 7,
  PAUSING: 8,
  PAUSED: 9,
  STOPPING: 10,
  STOPPED: 11,
  DESTROYING: 12,
  DESTROYED: 13,

  properties: new Map([
    [1, {name: 'initialized'}],
    [2, {name: 'creating'}],
    [3, {name: 'created'}],
    [4, {name: 'starting'}],
    [5, {name: 'started'}],
    [6, {name: 'resuming'}],
    [7, {name: 'resumed'}],
    [8, {name: 'pausing'}],
    [9, {name: 'paused'}],
    [10, {name: 'stopping'}],
    [11, {name: 'stopped'}],
    [12, {name: 'destroying'}],
    [13, {name: 'destroyed'}],
  ]),
};
